import React from "react";
import Head from "next/head";
import Header from "../Header";

const MainContainer = ({ children, keywords }) => {
  return (
    <>
      <Head>
        <title>Главная</title>
        <meta
          name="description"
          content="Generated by create next app"
          keywords={"Unsplash, Image Stock, Test task" + keywords}
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        {children}
      </div>
    </>
  );
};

export default MainContainer;
